/*
  Permission schema audit.
  Run this first in the target database. It is read-only.
*/

SET NOCOUNT ON;

SELECT 'TB_PERFIL: null CODPERFIL' AS CHECK_NAME, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFIL
WHERE CODPERFIL IS NULL;

SELECT 'TB_PERFIL: duplicate CODPERFIL' AS CHECK_NAME, CODPERFIL, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFIL
GROUP BY CODPERFIL
HAVING COUNT_BIG(*) > 1;

SELECT 'TB_PERMISSOES_NEW: null CODPERMISSAO' AS CHECK_NAME, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERMISSOES_NEW
WHERE CODPERMISSAO IS NULL;

SELECT 'TB_PERMISSOES_NEW: duplicate CODPERMISSAO' AS CHECK_NAME, CODPERMISSAO, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERMISSOES_NEW
GROUP BY CODPERMISSAO
HAVING COUNT_BIG(*) > 1;

SELECT 'TB_PERFILPERMISSOES_NEW: null CODPERFIL' AS CHECK_NAME, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFILPERMISSOES_NEW
WHERE CODPERFIL IS NULL;

SELECT 'TB_PERFILPERMISSOES_NEW: null CODPERMISSAO' AS CHECK_NAME, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFILPERMISSOES_NEW
WHERE CODPERMISSAO IS NULL;

SELECT 'TB_PERFILPERMISSOES_NEW: duplicate profile permission' AS CHECK_NAME,
       CODPERFIL, CODPERMISSAO, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFILPERMISSOES_NEW
GROUP BY CODPERFIL, CODPERMISSAO
HAVING COUNT_BIG(*) > 1;

SELECT 'TB_PERFILPERMISSOES_NEW: invalid PERMITIDO' AS CHECK_NAME,
       PERMITIDO, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFILPERMISSOES_NEW
WHERE PERMITIDO IS NULL OR PERMITIDO NOT IN (0, 1)
GROUP BY PERMITIDO;

SELECT 'TB_PERFILPERMISSOES_NEW: orphan profile' AS CHECK_NAME,
       PP.CODPERFIL, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFILPERMISSOES_NEW AS PP
LEFT JOIN dbo.TB_PERFIL AS P ON P.CODPERFIL = PP.CODPERFIL
WHERE P.CODPERFIL IS NULL
GROUP BY PP.CODPERFIL;

SELECT 'TB_PERFILPERMISSOES_NEW: orphan permission' AS CHECK_NAME,
       PP.CODPERMISSAO, COUNT_BIG(*) AS TOTAL
FROM dbo.TB_PERFILPERMISSOES_NEW AS PP
LEFT JOIN dbo.TB_PERMISSOES_NEW AS P ON P.CODPERMISSAO = PP.CODPERMISSAO
WHERE P.CODPERMISSAO IS NULL
GROUP BY PP.CODPERMISSAO;
