/*
  Permission indexes.
  Run only after 001_audit_permission_integrity.sql returns no invalid rows.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_TB_PERFIL_CODPERFIL'
      AND object_id = OBJECT_ID(N'dbo.TB_PERFIL')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_TB_PERFIL_CODPERFIL
        ON dbo.TB_PERFIL (CODPERFIL);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_TB_PERMISSOES_NEW_CODPERMISSAO'
      AND object_id = OBJECT_ID(N'dbo.TB_PERMISSOES_NEW')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_TB_PERMISSOES_NEW_CODPERMISSAO
        ON dbo.TB_PERMISSOES_NEW (CODPERMISSAO);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'UX_TB_PERFILPERMISSOES_NEW_PROFILE_PERMISSION'
      AND object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_TB_PERFILPERMISSOES_NEW_PROFILE_PERMISSION
        ON dbo.TB_PERFILPERMISSOES_NEW (CODPERFIL, CODPERMISSAO);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = N'IX_TB_PERFILPERMISSOES_NEW_PERMISSION'
      AND object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_TB_PERFILPERMISSOES_NEW_PERMISSION
        ON dbo.TB_PERFILPERMISSOES_NEW (CODPERMISSAO)
        INCLUDE (CODPERFIL, PERMITIDO, ID);
END;

COMMIT TRANSACTION;
