/*
  Permission relationships and value validation.
  Run after 001 and 002 succeed in the target database.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF EXISTS (SELECT 1 FROM dbo.TB_PERFIL WHERE CODPERFIL IS NULL)
    THROW 51001, 'TB_PERFIL contains null CODPERFIL values.', 1;

IF EXISTS (SELECT 1 FROM dbo.TB_PERMISSOES_NEW WHERE CODPERMISSAO IS NULL)
    THROW 51002, 'TB_PERMISSOES_NEW contains null CODPERMISSAO values.', 1;

IF EXISTS (
    SELECT 1
    FROM dbo.TB_PERFILPERMISSOES_NEW
    WHERE CODPERFIL IS NULL OR CODPERMISSAO IS NULL
)
    THROW 51003, 'Permission links contain null foreign key values.', 1;

IF EXISTS (
    SELECT 1
    FROM dbo.TB_PERFILPERMISSOES_NEW
    WHERE PERMITIDO IS NULL OR PERMITIDO NOT IN (0, 1)
)
    THROW 51004, 'PERMITIDO must contain only 0 or 1.', 1;

IF EXISTS (
    SELECT 1
    FROM dbo.TB_PERFILPERMISSOES_NEW AS PP
    LEFT JOIN dbo.TB_PERFIL AS P ON P.CODPERFIL = PP.CODPERFIL
    WHERE P.CODPERFIL IS NULL
)
    THROW 51005, 'Permission links contain orphan profiles.', 1;

IF EXISTS (
    SELECT 1
    FROM dbo.TB_PERFILPERMISSOES_NEW AS PP
    LEFT JOIN dbo.TB_PERMISSOES_NEW AS P ON P.CODPERMISSAO = PP.CODPERMISSAO
    WHERE P.CODPERMISSAO IS NULL
)
    THROW 51006, 'Permission links contain orphan permissions.', 1;

BEGIN TRANSACTION;

/* SQL Server requires dependent indexes to be removed before changing
   nullable columns to NOT NULL. They are recreated below. */
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TB_PERFIL_CODPERFIL'
           AND object_id = OBJECT_ID(N'dbo.TB_PERFIL'))
    DROP INDEX UX_TB_PERFIL_CODPERFIL ON dbo.TB_PERFIL;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TB_PERMISSOES_NEW_CODPERMISSAO'
           AND object_id = OBJECT_ID(N'dbo.TB_PERMISSOES_NEW'))
    DROP INDEX UX_TB_PERMISSOES_NEW_CODPERMISSAO ON dbo.TB_PERMISSOES_NEW;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_TB_PERFILPERMISSOES_NEW_PROFILE_PERMISSION'
           AND object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW'))
    DROP INDEX UX_TB_PERFILPERMISSOES_NEW_PROFILE_PERMISSION
        ON dbo.TB_PERFILPERMISSOES_NEW;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TB_PERFILPERMISSOES_NEW_PERMISSION'
           AND object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW'))
    DROP INDEX IX_TB_PERFILPERMISSOES_NEW_PERMISSION
        ON dbo.TB_PERFILPERMISSOES_NEW;

IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.TB_PERFIL')
      AND name = N'CODPERFIL'
      AND is_nullable = 1
)
    ALTER TABLE dbo.TB_PERFIL ALTER COLUMN CODPERFIL int NOT NULL;

IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.TB_PERMISSOES_NEW')
      AND name = N'CODPERMISSAO'
      AND is_nullable = 1
)
    ALTER TABLE dbo.TB_PERMISSOES_NEW ALTER COLUMN CODPERMISSAO int NOT NULL;

IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
      AND name = N'CODPERFIL'
      AND is_nullable = 1
)
    ALTER TABLE dbo.TB_PERFILPERMISSOES_NEW ALTER COLUMN CODPERFIL int NOT NULL;

IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
      AND name = N'CODPERMISSAO'
      AND is_nullable = 1
)
    ALTER TABLE dbo.TB_PERFILPERMISSOES_NEW ALTER COLUMN CODPERMISSAO int NOT NULL;

IF EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
      AND name = N'PERMITIDO'
      AND is_nullable = 1
)
    ALTER TABLE dbo.TB_PERFILPERMISSOES_NEW ALTER COLUMN PERMITIDO int NOT NULL;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_TB_PERFIL_CODPERFIL'
      AND object_id = OBJECT_ID(N'dbo.TB_PERFIL')
)
    CREATE UNIQUE NONCLUSTERED INDEX UX_TB_PERFIL_CODPERFIL
        ON dbo.TB_PERFIL (CODPERFIL);

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_TB_PERMISSOES_NEW_CODPERMISSAO'
      AND object_id = OBJECT_ID(N'dbo.TB_PERMISSOES_NEW')
)
    CREATE UNIQUE NONCLUSTERED INDEX UX_TB_PERMISSOES_NEW_CODPERMISSAO
        ON dbo.TB_PERMISSOES_NEW (CODPERMISSAO);

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'UX_TB_PERFILPERMISSOES_NEW_PROFILE_PERMISSION'
      AND object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
)
    CREATE UNIQUE NONCLUSTERED INDEX UX_TB_PERFILPERMISSOES_NEW_PROFILE_PERMISSION
        ON dbo.TB_PERFILPERMISSOES_NEW (CODPERFIL, CODPERMISSAO);

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_TB_PERFILPERMISSOES_NEW_PERMISSION'
      AND object_id = OBJECT_ID(N'dbo.TB_PERFILPERMISSOES_NEW')
)
    CREATE NONCLUSTERED INDEX IX_TB_PERFILPERMISSOES_NEW_PERMISSION
        ON dbo.TB_PERFILPERMISSOES_NEW (CODPERMISSAO)
        INCLUDE (CODPERFIL, PERMITIDO, ID);

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'FK_TB_PERFILPERMISSOES_NEW_PERFIL'
)
BEGIN
    ALTER TABLE dbo.TB_PERFILPERMISSOES_NEW
        ADD CONSTRAINT FK_TB_PERFILPERMISSOES_NEW_PERFIL
        FOREIGN KEY (CODPERFIL) REFERENCES dbo.TB_PERFIL (CODPERFIL);
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'FK_TB_PERFILPERMISSOES_NEW_PERMISSAO'
)
BEGIN
    ALTER TABLE dbo.TB_PERFILPERMISSOES_NEW
        ADD CONSTRAINT FK_TB_PERFILPERMISSOES_NEW_PERMISSAO
        FOREIGN KEY (CODPERMISSAO) REFERENCES dbo.TB_PERMISSOES_NEW (CODPERMISSAO);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = N'CK_TB_PERFILPERMISSOES_NEW_PERMITIDO'
)
BEGIN
    ALTER TABLE dbo.TB_PERFILPERMISSOES_NEW
        ADD CONSTRAINT CK_TB_PERFILPERMISSOES_NEW_PERMITIDO
        CHECK (PERMITIDO IN (0, 1));
END;

COMMIT TRANSACTION;
