/*
  Creates the Azure table used by TB_LOTES.TIPOBAIA.
  Initial values from the local Dados.db:
    1 = AGRUPAMENTO
    2 = BEZERREIRO
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.TB_TIPOBAIA', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_TIPOBAIA
    (
        CODTIPOBAIA int NOT NULL,
        DESCRICAO nvarchar(50) NOT NULL,
        CONSTRAINT PK_TB_TIPOBAIA PRIMARY KEY CLUSTERED (CODTIPOBAIA)
    );
END;

IF NOT EXISTS (
    SELECT 1 FROM dbo.TB_TIPOBAIA WHERE CODTIPOBAIA = 1
)
BEGIN
    INSERT INTO dbo.TB_TIPOBAIA (CODTIPOBAIA, DESCRICAO)
    VALUES (1, N'AGRUPAMENTO');
END;

IF NOT EXISTS (
    SELECT 1 FROM dbo.TB_TIPOBAIA WHERE CODTIPOBAIA = 2
)
BEGIN
    INSERT INTO dbo.TB_TIPOBAIA (CODTIPOBAIA, DESCRICAO)
    VALUES (2, N'BEZERREIRO');
END;

COMMIT TRANSACTION;
